var App = require('./app');

App.Router.map(function() {

  // generated by ember-generate --scaffold
  this.resource('clients');
  this.resource('client', {path: '/clients/:client_id'});
  this.route('edit_client', {path: '/clients/:client_id/edit'});
  this.route('new_client', {path: '/clients/new'});
  // end generated routes


  // generated by ember-generate --scaffold
  this.resource('people');
  this.resource('person', {path: '/people/:person_id'});
  this.route('edit_person', {path: '/people/:person_id/edit'});
  this.route('new_person', {path: '/people/new'});
  // end generated routes


});

