// This file is auto-generated by `ember build`.
// You should not modify it.

require('./vendor/jquery');
require('./vendor/handlebars');
require('./vendor/ember');
require('./vendor/ember-data');
require('./templates');

var App = window.App = require('./app');

App.store = require('./store');

App.ClientController = require('./controllers/client_controller');
App.EditClientController = require('./controllers/edit_client_controller');
App.EditPersonController = require('./controllers/edit_person_controller');
App.NewClientController = require('./controllers/new_client_controller');
App.NewPersonController = require('./controllers/new_person_controller');
App.PersonController = require('./controllers/person_controller');
App.Client = require('./models/client');
App.Person = require('./models/person');
App.ClientsRoute = require('./routes/clients_route');
App.NewClientRoute = require('./routes/new_client_route');
App.NewPersonRoute = require('./routes/new_person_route');
App.PeopleRoute = require('./routes/people_route');

require('./routes');

